server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /downloads/ {
        add_header Content-Disposition 'attachment';
        add_header X-Content-Type-Options nosniff;
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
    gzip_min_length 1024;
}
